import { User, Role } from "./user.entity";
import { v4 } from 'uuid';

export let data: Array<User> = [
	{
		id: v4(),
		firstName: 'Carlos',
		lastName: 'González',
		address: 'Calle Falsa 123',
		phone: '+34123456789',
		email: 'carlos.gonzalez@example.com',
		imageUrl: '',
		role: Role.ADMIN,
		authorized: true,
	},
	{
		id: v4(),
		firstName: 'María',
		lastName: 'López',
		address: 'Avenida Central 45',
		phone: '+34111222333',
		email: 'maria.lopez@example.com',
		imageUrl: '',
		role: Role.ADMIN,
		authorized: true,
	},
	{
		id: v4(),
		firstName: 'Ana',
		lastName: 'Martínez',
		address: 'Plaza Mayor 1',
		phone: '+34199887766',
		email: 'ana.martinez@example.com',
		imageUrl: '',
		role: Role.RRHH,
		authorized: true,
	},
	{
		id: v4(),
		firstName: 'Jorge',
		lastName: 'Sánchez',
		address: 'Calle Nueva 9',
		phone: '+34122334455',
		email: 'jorge.sanchez@example.com',
		imageUrl: '',
		role: Role.RRHH,
		authorized: true,
	},
	{
		id: v4(),
		firstName: 'Laura',
		lastName: 'Fernández',
		address: 'Calle Olmo 7',
		phone: '+34166778899',
		email: 'laura.fernandez@example.com',
		imageUrl: '',
		role: Role.SALES,
		authorized: false,
	},
	{
		id: v4(),
		firstName: 'Diego',
		lastName: 'Ramírez',
		address: 'Camino Real 20',
		phone: '+34155667788',
		email: 'diego.ramirez@example.com',
		imageUrl: '',
		role: Role.SALES,
		authorized: false,
	},
	{
		id: v4(),
		firstName: 'Patricia',
		lastName: 'Ruiz',
		address: 'Boulevard 12',
		phone: '+34144556677',
		email: 'patricia.ruiz@example.com',
		imageUrl: '',
		role: Role.SALES,
		authorized: false,
	},
	{
		id: v4(),
		firstName: 'Miguel',
		lastName: 'Torres',
		address: 'Ruta 5 km 10',
		phone: '+34133445566',
		email: 'miguel.torres@example.com',
		imageUrl: '',
		role: Role.SALES,
		authorized: false,
	},
	{
		id: v4(),
		firstName: 'Sofía',
		lastName: 'Castillo',
		address: 'Paseo de la Castellana 100',
		phone: '+34122331144',
		email: 'sofia.castillo@example.com',
		imageUrl: '',
		role: Role.SALES,
		authorized: true,
	},
	{
		id: v4(),
		firstName: 'Andrés',
		lastName: 'Vega',
		address: 'Calle Industria 3',
		phone: '+34177889900',
		email: 'andres.vega@example.com',
		imageUrl: '',
		role: Role.CLIENT,
		authorized: false,
	},
	{
		id: v4(),
		firstName: 'Lucía',
		lastName: 'Molina',
		address: 'Avenida Mar 88',
		phone: '+34166770011',
		email: 'lucia.molina@example.com',
		role: Role.CLIENT,
		authorized: false,
		imageUrl: '',
	},
];