import { Order, PaymentMethod } from "./order.entity";
import { products } from "../products/products.data";
import { data as users } from "../users/users.data";
import { Role } from "../users/user.entity";
import { v4 } from 'uuid';

const clients = users.filter((u) => u.role === Role.CLIENT);

const price = (i: number) => (products[i]?.price ?? 0);

export let orders: Array<Order> = [
	{
		id: v4(),
		products: [products[0]],
		client: clients[0] ?? users[10],
		address: (clients[0] ?? users[10]).address,
		totalPrice: price(0) * 10,
		paymentMethod: PaymentMethod.CASH,
		createdAt: new Date(),
	},
	{
		id: v4(),
		products: [products[1], products[0]],
		client: clients[1] ?? users[11],
		address: (clients[1] ?? users[11]).address,
		totalPrice: price(1) * 5 + price(0) * 20,
		paymentMethod: PaymentMethod.CREDIT_CARD,
		createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24),
	},
	{
		id: v4(),
		products: [products[2]],
		client: clients[0] ?? users[10],
		address: (clients[0] ?? users[10]).address,
		totalPrice: price(2) * 3,
		paymentMethod: PaymentMethod.DEBIT_CARD,
		createdAt: new Date(Date.now() - 1000 * 60 * 60 * 48),
	},
	{
		id: v4(),
		products: [products[0], products[1], products[2]],
		client: clients[1] ?? users[11],
		address: (clients[1] ?? users[11]).address,
		totalPrice: price(0) * 2 + price(1) * 2 + price(2) * 1,
		paymentMethod: PaymentMethod.PAYPAL,
		createdAt: new Date(Date.now() - 1000 * 60 * 60 * 72),
	},
	{
		id: v4(),
		products: [products[1]],
		client: clients[0] ?? users[10],
		address: (clients[0] ?? users[10]).address,
		totalPrice: price(1) * 12,
		paymentMethod: PaymentMethod.CASH,
		createdAt: new Date(Date.now() - 1000 * 60 * 60 * 96),
	},
	{
		id: v4(),
		products: [products[3]],
		client: clients[2] ?? users[12],
		address: (clients[2] ?? users[12]).address,
		totalPrice: price(3) * 7,
		paymentMethod: PaymentMethod.CREDIT_CARD,
		createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5),
	},
	{
		id: v4(),
		products: [products[0], products[4]],
		client: clients[3] ?? users[13],
		address: (clients[3] ?? users[13]).address,
		totalPrice: price(0) * 50 + price(4) * 10,
		paymentMethod: PaymentMethod.CASH,
		createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 6),
	},
	{
		id: v4(),
		products: [products[5]],
		client: clients[4] ?? users[14],
		address: (clients[4] ?? users[14]).address,
		totalPrice: price(5) * 200,
		paymentMethod: PaymentMethod.DEBIT_CARD,
		createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 7),
	},
	{
		id: v4(),
		products: [products[6], products[7]],
		client: clients[5] ?? users[15],
		address: (clients[5] ?? users[15]).address,
		totalPrice: price(6) * 500 + price(7) * 20,
		paymentMethod: PaymentMethod.PAYPAL,
		createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 8),
	},
	{
		id: v4(),
		products: [products[8]],
		client: clients[6] ?? users[16],
		address: (clients[6] ?? users[16]).address,
		totalPrice: price(8) * 30,
		paymentMethod: PaymentMethod.CREDIT_CARD,
		createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 9),
	},
	{
		id: v4(),
		products: [products[9], products[10]],
		client: clients[7] ?? users[10],
		address: (clients[7] ?? users[10]).address,
		totalPrice: price(9) * 12 + price(10) * 6,
		paymentMethod: PaymentMethod.DEBIT_CARD,
		createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 10),
	},
	{
		id: v4(),
		products: [products[11]],
		client: clients[8] ?? users[11],
		address: (clients[8] ?? users[11]).address,
		totalPrice: price(11) * 15,
		paymentMethod: PaymentMethod.CASH,
		createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 11),
	},
	{
		id: v4(),
		products: [products[12], products[0]],
		client: clients[9] ?? users[12],
		address: (clients[9] ?? users[12]).address,
		totalPrice: price(12) * 40 + price(0) * 100,
		paymentMethod: PaymentMethod.CREDIT_CARD,
		createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 12),
	},
	{
		id: v4(),
		products: [products[13]],
		client: clients[10] ?? users[13],
		address: (clients[10] ?? users[13]).address,
		totalPrice: price(13) * 8,
		paymentMethod: PaymentMethod.PAYPAL,
		createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 13),
	},
	{
		id: v4(),
		products: [products[14], products[15]],
		client: clients[11] ?? users[14],
		address: (clients[11] ?? users[14]).address,
		totalPrice: price(14) * 2 + price(15) * 3,
		paymentMethod: PaymentMethod.DEBIT_CARD,
		createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 14),
	},
	{
		id: v4(),
		products: [products[16]],
		client: clients[12] ?? users[15],
		address: (clients[12] ?? users[15]).address,
		totalPrice: price(16) * 1,
		paymentMethod: PaymentMethod.CASH,
		createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 15),
	},
	{
		id: v4(),
		products: [products[17], products[18]],
		client: clients[13] ?? users[16],
		address: (clients[13] ?? users[16]).address,
		totalPrice: price(17) * 4 + price(18) * 10,
		paymentMethod: PaymentMethod.CREDIT_CARD,
		createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 16),
	},
	{
		id: v4(),
		products: [products[19]],
		client: clients[14] ?? users[10],
		address: (clients[14] ?? users[10]).address,
		totalPrice: price(19) * 2,
		paymentMethod: PaymentMethod.PAYPAL,
		createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 17),
	},
	{
		id: v4(),
		products: [products[2], products[5]],
		client: clients[15] ?? users[11],
		address: (clients[15] ?? users[11]).address,
		totalPrice: price(2) * 6 + price(5) * 30,
		paymentMethod: PaymentMethod.DEBIT_CARD,
		createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 18),
	},
	{
		id: v4(),
		products: [products[1]],
		client: clients[16] ?? users[12],
		address: (clients[16] ?? users[12]).address,
		totalPrice: price(1) * 24,
		paymentMethod: PaymentMethod.CASH,
		createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 19),
	},
	{
		id: v4(),
		products: [products[0], products[0], products[0]],
		client: clients[0] ?? users[10],
		address: (clients[0] ?? users[10]).address,
		totalPrice: price(0) * 300,
		paymentMethod: PaymentMethod.CREDIT_CARD,
		createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 20),
	},
	{
		id: v4(),
		products: [products[4]],
		client: clients[1] ?? users[11],
		address: (clients[1] ?? users[11]).address,
		totalPrice: price(4) * 25,
		paymentMethod: PaymentMethod.PAYPAL,
		createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 21),
	},
	{
		id: v4(),
		products: [products[7], products[8]],
		client: clients[2] ?? users[12],
		address: (clients[2] ?? users[12]).address,
		totalPrice: price(7) * 15 + price(8) * 40,
		paymentMethod: PaymentMethod.DEBIT_CARD,
		createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 22),
	},
	{
		id: v4(),
		products: [products[11]],
		client: clients[3] ?? users[13],
		address: (clients[3] ?? users[13]).address,
		totalPrice: price(11) * 6,
		paymentMethod: PaymentMethod.CASH,
		createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 23),
	},
	{
		id: v4(),
		products: [products[13], products[14]],
		client: clients[4] ?? users[14],
		address: (clients[4] ?? users[14]).address,
		totalPrice: price(13) * 3 + price(14) * 5,
		paymentMethod: PaymentMethod.CREDIT_CARD,
		createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 24),
	},
	{
		id: v4(),
		products: [products[15]],
		client: clients[5] ?? users[15],
		address: (clients[5] ?? users[15]).address,
		totalPrice: price(15) * 10,
		paymentMethod: PaymentMethod.PAYPAL,
		createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 25),
	},
	{
		id: v4(),
		products: [products[16], products[17]],
		client: clients[6] ?? users[16],
		address: (clients[6] ?? users[16]).address,
		totalPrice: price(16) * 2 + price(17) * 1,
		paymentMethod: PaymentMethod.DEBIT_CARD,
		createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 26),
	},
	{
		id: v4(),
		products: [products[18]],
		client: clients[7] ?? users[10],
		address: (clients[7] ?? users[10]).address,
		totalPrice: price(18) * 60,
		paymentMethod: PaymentMethod.CASH,
		createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 27),
	},
	{
		id: v4(),
		products: [products[19], products[0]],
		client: clients[8] ?? users[11],
		address: (clients[8] ?? users[11]).address,
		totalPrice: price(19) * 1 + price(0) * 20,
		paymentMethod: PaymentMethod.CREDIT_CARD,
		createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 28),
	},
	{
		id: v4(),
		products: [products[2], products[3], products[4]],
		client: clients[9] ?? users[12],
		address: (clients[9] ?? users[12]).address,
		totalPrice: price(2) * 2 + price(3) * 1 + price(4) * 5,
		paymentMethod: PaymentMethod.PAYPAL,
		createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 29),
	},
	{
		id: v4(),
		products: [products[5]],
		client: clients[10] ?? users[13],
		address: (clients[10] ?? users[13]).address,
		totalPrice: price(5) * 100,
		paymentMethod: PaymentMethod.DEBIT_CARD,
		createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 30),
	},
	{
		id: v4(),
		products: [products[6], products[7], products[8]],
		client: clients[11] ?? users[14],
		address: (clients[11] ?? users[14]).address,
		totalPrice: price(6) * 20 + price(7) * 10 + price(8) * 25,
		paymentMethod: PaymentMethod.CASH,
		createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 31),
	},
	{
		id: v4(),
		products: [products[9]],
		client: clients[12] ?? users[15],
		address: (clients[12] ?? users[15]).address,
		totalPrice: price(9) * 40,
		paymentMethod: PaymentMethod.CREDIT_CARD,
		createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 32),
	},
	{
		id: v4(),
		products: [products[10], products[11]],
		client: clients[13] ?? users[16],
		address: (clients[13] ?? users[16]).address,
		totalPrice: price(10) * 12 + price(11) * 8,
		paymentMethod: PaymentMethod.PAYPAL,
		createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 33),
	},
	{
		id: v4(),
		products: [products[12]],
		client: clients[14] ?? users[10],
		address: (clients[14] ?? users[10]).address,
		totalPrice: price(12) * 10,
		paymentMethod: PaymentMethod.DEBIT_CARD,
		createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 34),
	},
	{
		id: v4(),
		products: [products[13], products[14], products[15]],
		client: clients[15] ?? users[11],
		address: (clients[15] ?? users[11]).address,
		totalPrice: price(13) * 2 + price(14) * 6 + price(15) * 4,
		paymentMethod: PaymentMethod.CREDIT_CARD,
		createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 35),
	},
	{
		id: v4(),
		products: [products[16], products[17], products[18], products[19]],
		client: clients[16] ?? users[12],
		address: (clients[16] ?? users[12]).address,
		totalPrice: price(16) * 3 + price(17) * 2 + price(18) * 20 + price(19) * 1,
		paymentMethod: PaymentMethod.CASH,
		createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 36),
	},
];
