import { Product, Unit } from "./product.entity";
import { v4 } from 'uuid';

export let products: Array<Product> = [
	{
		id: v4(),
		name: 'Ladrillo común',
		description: 'Ladrillo cerámico rojo para construcción general.',
		reference: 'LC-001',
		price: 0.45,
		stock: 1000,
		imageUrl: 'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcTO790JaLW-keIWfXCr57uqfdsfRXM5eIvXHQ7szGsL-n4uf5QEerS-RNhgHnvH0R9VamLFCi_E8jTxSqGJgIjeZPA-TjmzqbuVCBkP3hPleMkXxqXeu9uqV8CAPQRgfzKI-oXV6gRawQ&usqp=CAc',
		unit: Unit.UNIT,
	},
	{
		id: v4(),
		name: 'Ladrillo perforado',
		description: 'Ladrillo perforado para muros interiores y tabiques.',
		reference: 'LP-002',
		price: 0.55,
		stock: 750,
		imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQfwYTy7lbvn6MSdC1POqM5kC8x36y105pW2Q&s',
		unit: Unit.UNIT,
	},
	{
		id: v4(),
		name: 'Ladrillo refractario',
		description: 'Ladrillo refractario para altas temperaturas (hornos, chimeneas).',
		reference: 'LR-003',
		price: 1.25,
		stock: 200,
		imageUrl: 'https://arcencohogar.vtexassets.com/arquivos/ids/279103/1129110.jpg?v=637651612412200000',
		unit: Unit.UNIT,
	},
	{
		id: v4(),
		name: 'Cemento Portland',
		description: 'Bolsa de cemento Portland de 42.5 kg para construcción general.',
		reference: 'CEM-001',
		price: 5.5,
		stock: 500,
		imageUrl: 'https://www.titaniccenter.com/cdn/shop/products/CEMENTOPORTLANDGRISTIPOISACO42.5KGCSC.jpg?crop=center&height=1200&v=1666873895&width=1200',
		unit: Unit.UNIT,
	},
	{
		id: v4(),
		name: 'Varilla de acero',
		description: 'Varilla corrugada de acero para armado de estructuras (precio por metro).',
		reference: 'VAR-010',
		price: 2.5,
		stock: 10000,
		imageUrl: 'https://www.acesco.com.co/wp-content/uploads/2024/09/Acesco_Varillas.webp',
		unit: Unit.METER,
	},
	{
		id: v4(),
		name: 'Arena fina',
		description: 'Arena fina para morteros y mezclas (precio por kilogramo).',
		reference: 'ARE-020',
		price: 0.02,
		stock: 200000,
		imageUrl: 'https://arcencohogar.vtexassets.com/arquivos/ids/278586-800-800?v=637651609278370000&width=800&height=800&aspect=true',
		unit: Unit.KILOGRAM,
	},
	{
		id: v4(),
		name: 'Grava',
		description: 'Grava para mezclas y rellenos (precio por kilogramo).',
		reference: 'GRA-030',
		price: 0.015,
		stock: 150000,
		imageUrl: 'https://media.falabella.com/sodimacCO/368268/public',
		unit: Unit.KILOGRAM,
	},
	{
		id: v4(),
		name: 'Pintura blanca',
		description: 'Pintura látex blanco para interiores (precio por litro).',
		reference: 'PNT-040',
		price: 6.0,
		stock: 300,
		imageUrl: 'https://media.falabella.com/sodimacCO/25440_01/w=800,h=800,fit=pad',
		unit: Unit.LITER,
	},
	{
		id: v4(),
		name: 'Baldosa cerámica 30x30',
		description: 'Baldosa cerámica esmaltada 30x30 cm para pisos y revestimientos.',
		reference: 'TIL-050',
		price: 2.75,
		stock: 1000,
		imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSoW-BH8xG4Qp78ov8lzOcFWiKiFIFgOQIs1A&s',
		unit: Unit.UNIT,
	},
	{
		id: v4(),
		name: 'Tubo PVC',
		description: 'Tubo PVC para instalaciones hidráulicas (precio por metro).',
		reference: 'PVC-060',
		price: 1.2,
		stock: 2000,
		imageUrl: 'https://media.falabella.com/sodimacCO/240898_1/w=1160',
		unit: Unit.METER,
	},
	{
		id: v4(),
		name: 'Tabla de madera',
		description: 'Tabla de madera tratada para encofrados y estructuras (precio por metro).',
		reference: 'MAD-070',
		price: 3.5,
		stock: 5000,
		imageUrl: 'https://www.tymforest.com/imagesv2/tymforest/trim:white/600/943dd342-63bf-4f06-a8f6-c3d5ff7e89c9/PNN2-01_.jpg',
		unit: Unit.METER,
	},
	{
		id: v4(),
		name: 'Yeso saco',
		description: 'Saco de yeso para enlucidos y acabados.',
		reference: 'YES-080',
		price: 4.0,
		stock: 400,
		imageUrl: 'https://media.falabella.com/sodimacCO/60981/public',
		unit: Unit.UNIT,
	},
	{
		id: v4(),
		name: 'Bloque de concreto',
		description: 'Bloque de concreto estándar para muros.',
		reference: 'BLO-090',
		price: 0.95,
		stock: 2000,
		imageUrl: 'https://arciaceros.com.co/wp-content/uploads/2015/12/bloque-concreto.png',
		unit: Unit.UNIT,
	},
	{
		id: v4(),
		name: 'Clavos caja',
		description: 'Caja de clavos para construcción.',
		reference: 'CLA-110',
		price: 3.2,
		stock: 600,
		imageUrl: 'https://camejia.com/wp-content/uploads/2023/08/liso-concreto.jpg',
		unit: Unit.UNIT,
	},
	{
		id: v4(),
		name: 'Tornillos caja',
		description: 'Caja de tornillos varios.',
		reference: 'TOR-120',
		price: 4.5,
		stock: 600,
		imageUrl: 'https://http2.mlstatic.com/D_NQ_NP_967382-MCO91742703074_092025-O.webp',
		unit: Unit.UNIT,
	},
	{
		id: v4(),
		name: 'Adhesivo cementicio',
		description: 'Adhesivo cementicio para colocación de cerámicos.',
		reference: 'ADH-130',
		price: 12.0,
		stock: 250,
		imageUrl: 'https://sikabrasil.com.br/sikaguia/co/co-SikaCeram-Flex-00764271.png',
		unit: Unit.UNIT,
	},
	{
		id: v4(),
		name: 'Sellador silicona',
		description: 'Silicona selladora para juntas y acabados.',
		reference: 'SEL-140',
		price: 2.2,
		stock: 800,
		imageUrl: 'https://http2.mlstatic.com/D_Q_NP_684403-MLA95085443166_102025-O.webp',
		unit: Unit.UNIT,
	},
	{
		id: v4(),
		name: 'Malla electrosoldada',
		description: 'Malla electrosoldada para refuerzo de pavimentos.',
		reference: 'MEL-150',
		price: 45.0,
		stock: 120,
		imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ0D87tyqLwQiRQ-HauJ6eo__vMiNjAq6AF1g&s',
		unit: Unit.UNIT,
	},
];